# ========================================
# PERFIL DE PRODUCCION
# ========================================

# Logging optimizado para produccion
logging.level.root=WARN
logging.level.com.challenge.product=INFO

# Desactivar logs SQL en produccion
spring.jpa.show-sql=false

# Desactivar consola H2 por seguridad
spring.h2.console.enabled=false

# URL del servicio de inventario en produccion
inventory.service.base-url=${INVENTORY_SERVICE_URL:http://inventory-service:8082}

# Configuracion de seguridad y optimizacion
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

